### ISSUE TITLE
Question: Any idea on how to adapt this plugin to lift module dependencies

### ISSUE THREAD

**Issue by adjavaherian** [soundcloud/move-to-parent-merging-webpack-plugin#2]
I'm trying to write a sass plugin that:

a. is instantiated from a webpack loader
b. recursively gets the sass dependencies of the entry (passed from loader)
c. filters all the dependencies based on a file extension regex
d. does not emit a bundle, but rather returns an object back to the loader
e. injects the object back into the entry module

I've got something working with inspiration from this plugin, but I'm at a loss as to how to inject the css output back into the entry module (lifting).

Here's the example.  (https://github.com/adjavaherian/sass-lifter-loader)[https://github.com/adjavaherian/sass-lifter-loader]

I noticed that you use chunk.removeModule and chunk.addModule, but when I try those, it doesn't seem to effect my module list.  Any ideas?

Thanks, 

Amir

**Comment by bruderstein** [comment]
Closing this old issue - probably isn't the right place for this kind of question.
